In [20]:
import yfinance as yf
import pandas as pd

In [151]:
data = yf.download("AAPL", end='2023-07-10')
data = data.reset_index()

[*********************100%***********************]  1 of 1 completed


In [152]:
data.set_index('Date').asfreq('b')
data['Date'].dtype

dtype('<M8[ns]')

In [58]:
data.columns.difference(['Close'])

Index(['Adj Close', 'Date', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [62]:
import numpy as np

In [84]:
data['Close']

0          0.128348
1          0.121652
2          0.112723
3          0.115513
4          0.118862
            ...    
10726    193.970001
10727    192.460007
10728    191.330002
10729    191.809998
10730    190.679993
Name: Close, Length: 10731, dtype: float64

In [117]:
new_df = pd.DataFrame({'close' : data['Close']})
for i in range(1, n_features+1):
    new_df[i] = new_df['close'].shift(i)
new_df.dropna(inplace=True)
new_df.drop('close', axis=1, inplace=True)
new_df = new_df.values
array= np.array(new_df)
array.shape
# array = array.reshape(-1, 1, n_features)
# array.shape

(10729, 2)

In [112]:
n_features = 2
base.shape[0]
new = pd.DataFrame
new

pandas.core.frame.DataFrame

In [113]:
data[['Open', 'Close']].apply(np.array, axis=1)

0          [0.1283479928970337, 0.1283479928970337]
1        [0.12221000343561172, 0.12165199965238571]
2         [0.1132809966802597, 0.11272300034761429]
3        [0.11551299691200256, 0.11551299691200256]
4        [0.11886200308799744, 0.11886200308799744]
                            ...                    
10726       [191.6300048828125, 193.97000122070312]
10727       [193.77999877929688, 192.4600067138672]
10728       [191.57000732421875, 191.3300018310547]
10729      [189.83999633789062, 191.80999755859375]
10730      [191.41000366210938, 190.67999267578125]
Length: 10731, dtype: object

In [114]:
import sklearn

In [115]:
from sklearn.preprocessing import MinMaxScaler

In [116]:
scaler = MinMaxScaler(feature_range = (0,1))

In [123]:
scaler.fit_transform(array)

array([[3.74095838e-04, 4.08625347e-04],
       [3.28051293e-04, 3.74095838e-04],
       [3.42438585e-04, 3.28051293e-04],
       ...,
       [9.92213348e-01, 1.00000000e+00],
       [9.86386205e-01, 9.92213348e-01],
       [9.88861419e-01, 9.86386205e-01]])

In [127]:
# scaler.fit_transform(array.reshape(-1))

In [128]:
from sklearn.model_selection import train_test_split

In [145]:
x, y = train_test_split(data, shuffle=False, test_size=0.2)
x = pd.DataFrame(x, columns=data.columns)
x

Date       Open       High        Low      Close  Adj Close  \
0    1980-12-12   0.128348   0.128906   0.128348   0.128348   0.099584   
1    1980-12-15   0.122210   0.122210   0.121652   0.121652   0.094388   
2    1980-12-16   0.113281   0.113281   0.112723   0.112723   0.087461   
3    1980-12-17   0.115513   0.116071   0.115513   0.115513   0.089625   
4    1980-12-18   0.118862   0.119420   0.118862   0.118862   0.092224   
...         ...        ...        ...        ...        ...        ...   
8579 2014-12-17  26.780001  27.459999  26.705000  27.352501  24.549709   
8580 2014-12-18  27.967501  28.162500  27.665001  28.162500  25.276714   
8581 2014-12-19  28.065001  28.309999  27.915001  27.945000  25.081505   
8582 2014-12-22  28.040001  28.372499  27.992500  28.235001  25.341782   
8583 2014-12-23  28.307501  28.332500  28.115000  28.135000  25.252031   

         Volume  
0     469033600  
1     175884800  
2     105728000  
3      86441600  
4      73449600  
...         ...  
8579  213647200  
8580  236024800  
8581  353719200  
8582  180670000  
8583  104113600  

[8584 rows x 7 columns]

In [150]:
x[['Close', 'Open', 'High']].values.reshape(-1, len(x.columns)-1)

array([[ 0.12834799,  0.12834799,  0.128906  ,  0.121652  ,  0.12221   ,
         0.12221   ],
       [ 0.112723  ,  0.113281  ,  0.113281  ,  0.115513  ,  0.115513  ,
         0.116071  ],
       [ 0.118862  ,  0.118862  ,  0.11942   ,  0.12611599,  0.12611599,
         0.126674  ],
       ...,
       [26.6875    , 26.59250069, 27.54000092, 27.35250092, 26.78000069,
        27.45999908],
       [28.16250038, 27.96750069, 28.16250038, 27.94499969, 28.06500053,
        28.30999947],
       [28.23500061, 28.04000092, 28.37249947, 28.13500023, 28.30750084,
        28.33250046]])

In [153]:
test = yf.download("AAPL", "2023-05-12")

[*********************100%***********************]  1 of 1 completed


In [155]:
test.columns

Index(['Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='object')

In [171]:
x = data[['Close', 'Open', 'Volume']].values.reshape(-1)
x

array([1.28347993e-01, 1.28347993e-01, 4.69033600e+08, ...,
       1.90679993e+02, 1.91410004e+02, 4.67780000e+07])

In [162]:
scaler = MinMaxScaler()

In [172]:
scaler.fit(x)

ValueError: Expected 2D array, got 1D array instead:
array=[1.28347993e-01 1.28347993e-01 4.69033600e+08 ... 1.90679993e+02
 1.91410004e+02 4.67780000e+07].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [164]:
scaler.transform(x)

array([[4.08625347e-04, 4.06146993e-04, 6.31981003e-02],
       [3.74095838e-04, 3.74463832e-04, 2.36989104e-02],
       [3.28051293e-04, 3.28373957e-04, 1.42459064e-02],
       ...,
       [9.86386205e-01, 9.88592435e-01, 6.32209255e-03],
       [9.88861419e-01, 9.79662439e-01, 6.07605531e-03],
       [9.83034275e-01, 9.87766525e-01, 6.30291889e-03]])

In [203]:
import datetime
import pandas
def get_stocks(dates, ticker):
    stocks = []
    for date in dates:
        date_obj = datetime.datetime.strptime(date, '%Y-%m-%d')
        start = date_obj.strftime('%Y-%m-%d')
        end = (date_obj + datetime.timedelta(days=1)).strftime('%Y-%m-%d')
        stock = yf.download(ticker, start=start, end=end)
        print(stock, "stock")
        entry = {
            "date": start,
            "close": stock['Open'].values[0]
        }
        stocks.append(entry)
    return pandas.DataFrame(stocks)

In [204]:
get_stocks(['2023-07-20'], 'AAPL')

[*********************100%***********************]  1 of 1 completed
                  Open        High    Low       Close   Adj Close    Volume
Date                                                                       
2023-07-20  195.089996  196.470001  192.5  193.130005  193.130005  59581200 stock


date       close
0  2023-07-20  195.089996